services:
  - type: web
    name: geolocalizador-lomas
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: GOOGLE_MAPS_API_KEY
        sync: false
